#
# gh-actions-luarocks | GitHub action workflow
#
# cspell:ignore luarocks, luajit, openresty, moonscript, pgmoon, leafo

name: test

on: [push]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        luaVersion: ["5.1.5", "5.2.4", "5.3.5", "luajit-2.0.5", "luajit-2.1.0-beta3", "luajit-openresty", "5.1", "5.4"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - run: npm install

      - uses: joelvaneenwyk/gh-actions-lua@main
        with:
          luaVersion: ${{ matrix.luaVersion }}

      - uses: joelvaneenwyk/gh-actions-luarocks@main

      - name: test lua
        run: lua -e 'print("hi from lua")'

      - name: test luarocks
        run: |
          echo $PATH
          env | grep LUA
          luarocks
          luarocks path
          luarocks install moonscript
          lua -e 'require("moon").p({1,2,3})'

  test-luarocks-2:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: joelvaneenwyk/gh-actions-lua@main
        with:
          luaVersion: "5.2"

      - uses: joelvaneenwyk/gh-actions-luarocks@main
        with:
          luaRocksVersion: "2.4.4"

      - name: test luarocks
        run: |
          luarocks --version
          luarocks path
          luarocks install moonscript
          lua -e 'require("moon").p({1,2,3})'

  test-macos:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4
      - uses: joelvaneenwyk/gh-actions-lua@main
      - uses: joelvaneenwyk/gh-actions-luarocks@main

      - name: test luarocks
        run: |
          echo $PATH
          env | grep LUA
          luarocks
          luarocks path
          luarocks install moonscript
          lua -e 'require("moon").p({1,2,3})'

  test-openresty:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: leafo/gh-actions-openresty@main
      - uses: joelvaneenwyk/gh-actions-luarocks@main
        with:
          withLuaPath: "/usr/local/openresty/luajit/"

      - name: test luarocks
        run: |
          echo $PATH
          env | grep LUA
          luarocks
          luarocks path
          luarocks install pgmoon
